# Generated by Django 5.2.4 on 2025-08-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_created_by_todo_updated_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('', 'Status'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=30),
        ),
    ]
